name: Test Github Actions
on:
  push:
    branches: [main]
jobs:
  tests:
    name: 'Perform unit and integration tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test
